### ISSUE TITLE
Null Safety Build Issue

### ISSUE THREAD

**Issue by mitchross** [Rukkaitto/mobichan#8] opened 2021-07-03 04:21 UTC
Can fix build issues with null safety with this fix

Remove
 # install_plugin: ^2.0.1

Add
  install_plugin: 
    git:
      url: https://github.com/mitchross/flutter_install_plugin.git
      
    I have a PR but doubt it will merge. https://github.com/hui-z/flutter_install_plugin/pull/54

**Comment by Rukkaitto** [comment] 2021-07-04 09:45
Fixed in 7dd1706e863ad1e349136279a1a89b841f340fc4. Removed updates for now, as it is probably caused by Google Play Protect.

**Closed by Rukkaitto** 2021-07-04 09:45 UTC
